version: 0.2

env:
  variables:
    CONTAINER_NAME: cloud-release-app

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing application dependencies"
      - npm install

  pre_build:
    commands:
      - echo "Getting AWS Account ID"
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "Logging into Amazon ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t cloud-release-management-v3 .
      - docker tag cloud-release-management-v3:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/cloud-release-management-v3:latest

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/cloud-release-management-v3:latest
      - echo "Creating ECS deployment artifact"
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/cloud-release-management-v3:latest" > imagedefinitions.json

artifacts:
  files: 
    - imagedefinitions.json